### ISSUE TITLE
Übersicht Seite

### ISSUE THREAD

**Issue by nadiabendinelli** [logrinto/IAD2017.schriftmuster#33]
Titel kann in 2 Grössen abgebildet werden:
H1 gross: 274 px
H1 klein: 190 px

Zwischentitel:
H2: 44 px

Lauftext:
H3: 20 px

___

Farben:
Bitte Hintergrund in 1 Farbe setzen, oder als Verlauf aus 2 Farben

_____

!!!!!
SVG: Text in Pfad umwandeln

**Comment by NMA93** [comment]
@logrinto/iad2017 

H1 gross 274px oder H1 klein 190 px kann nicht auf portrait svg 375 x 600 px abgebildet werden da zu gross.

<img width="554" alt="portrait_fontsize" src="https://user-images.githubusercontent.com/23292494/41820730-7f2dd5b8-77d6-11e8-80d5-ac296a6322fb.png">

**Lösungsvorschlag:** Jeweils unterschiedliche h1 für landscape und portrait: 

**h1 portrait:**  274px oder 190px
**h1 landscape:** 72px

**Comment by signalwerk** [comment]
wenn ich das richtig sehe, so kommen die vorgaben von @nadiabendinelli @stfffchs @wschoeck @pascaleva 
Was sagt ihr dazu? Nehmt ihr den von @NMA93 an?

**Comment by stfffchs** [comment]
Ja ich würde sagen, wir nehmen den Vorschlag an! Vielen Dank! 😊👍

**Comment by mariusbecker** [comment]
ay

MARIUS BECKER
Graphic Design

T: +41 44 283 60 90
E: marius@b-h.ch
W: b-h.ch <http://b-h.ch/>


BRAIN & HEART

COMMUNICATION
