### ISSUE TITLE
Source für Menü definieren

### ISSUE THREAD

**Issue by marc-hatt** [logrinto/IAD2017.schriftmuster#41]
Bei vielen Detailseiten reagiert das Menu nicht richtig und zeigt den falschen Font angewählt.

**Comment by signalwerk** [comment]
@marc-hatt ist das eine Korrektur für mich? Wie kann ich das Problem mit dem Menü reproduzieren.

Puncto aktive Schrift. Hast du https://github.com/logrinto/IAD2017.schriftmuster/issues/43 gesehen? Das wurde dort genau gelistet. Können wir hier also als erledigt sehen.

**Comment by marc-hatt** [comment]
@signalwerk Dieses Issue habe ich als reminder erstellt nachdem du mich darum gebeten hast. Es geht darum: Da alle vom Beispiel Ubuntu ausgehen ist bei vielen Detailseiten noch die Schrift Ubuntu ausgewählt im Menü und demnach unterstrichen, da im Code vermerkt wurde, welche Schrift im Menü angewählt ist. Standardmässig ist Ubuntu auf aktiv gestellt, jede Detailseite muss aber seine eigene Schrift auf aktiv stellen.

**Comment by marc-hatt** [comment]
[Bildschirmfoto 2018-07-05 um 10.19.33.pdf](https://github.com/logrinto/IAD2017.schriftmuster/files/2165644/Bildschirmfoto.2018-07-05.um.10.19.33.pdf)

**Comment by signalwerk** [comment]
Stimmt. Dein issue war auch vor dem #45. Aber da es sich nun ums selbe handelt, erlaube ich mir, diesen zu schliessen und den anderen noch offen zu lassen. Ich hoffe das ist ok für dich
