### ISSUE TITLE
Menu-Markierungen

### ISSUE THREAD

**Issue by mariusbecker** [logrinto/IAD2017.schriftmuster#43]
Bei diesen Schriftmustern bitte noch di Menumarkierung auf den eigenen Font machen:
Rambla
Open Sans
Roboto
Faustina
Raleway
Neuton

IBM zeigt 404
Bitter zeigt kein Hamburger, dafür eigenen Home-Button.

**Comment by signalwerk** [comment]
Bitte schaut euch die Erklärung in #41 von @marc-hatt an. Er macht noch einmal deutlich um was es geht.

**Comment by NMA93** [comment]
Ich bin die einzelnen Fonts nochmals durchgegangen (Stand: 22:50 Uhr) und folgende Personen müssen ihr Menü noch anpassen: @wschoeck @matthiasmeierkoch @nadiabendinelli @mariusbecker 

In eurem Index.html findet ihr am Ende die `<div class="navigation">` dort ist eine Liste `<li>` integriert mit allen Fonts.

Ein aktiver Font sieht folgendermassen aus:
`class="menu--list-item"><a class="menu--list-item-link  menu--list-item-link--active" aria-current="true" href="../fontname/index.html">fontname</a>`

Dies bitte auf euren eigenen Font übernehmen und «Fontname» mit eurem Font ersetzten. Mein Font > Ubuntu ist wie @marc-hatt erwähnt hat standardmässig aktiv. Bitte Ubuntu wie folgt überschreiben.

`<li class="menu--list-item"><a class="menu--list-item-link" aria-current="false" href="../ubuntu/index.html">Ubuntu</a></li>`

**Comment by NMA93** [comment]
Alles korrekt.
