### ISSUE TITLE
Unnötige Datei

### ISSUE THREAD

**Issue by signalwerk** [logrinto/IAD2017.schriftmuster#53]
@stfffchs @tioemayer Ich glaube durch den PR von @stfffchs gibt es nun diese Datei: https://github.com/logrinto/IAD2017.schriftmuster/blob/master/__FINAL__/fonts/barlow/index.html kann die weg? Oder was ist mit der?

**Comment by stfffchs** [comment]
Hey @signalwerk die kann weg, danke.

**Comment by signalwerk** [comment]
@stfffchs darf ich dich bitten dies zu tun? merci
