### ISSUE TITLE
Lato – Review

### ISSUE THREAD

**Issue by signalwerk** [logrinto/IAD2017.schriftmuster#63]
Hey @pascaleva hier noch ein paar Inputs zu deiner Schrift
* Bitte im Text Links setzen wo sinnvoll (SIL Open Font License verlinken, Google Fonts, ...)
* Der Text teils 1:1 von der [Typoberlin-Seite](http://www.typoberlin.de/2009/index.php?node_id=Dziedzic;3523&lang_id=1) kopiert. Weder war das die Aufgabe, noch ist es Legal.
* Das Ananas-Bild finde ich gelungen für Sommer
* Allenfalls kannst du beim «Multilingual» den Marienkäfer raus nehmen (da nur eine Markierung) und entweder das Multilingual in seiner Wirkung verstärken oder noch einen weiteren Aspekt dazu fügen.
* Quellen zum Text?

**Comment by pascaleva** [comment]
Danke für deine Inputs. Die Quellen sowie den Text passe ich noch an bzw. schreibe ihn in meinen Worten. Das Detailbild werde ich auch noch anschauen.

**Comment by signalwerk** [comment]
👌
