### ISSUE TITLE
IBM PLex – Review

### ISSUE THREAD

**Issue by signalwerk** [logrinto/IAD2017.schriftmuster#64]
@stfffchs hier ein paar Inputs zu deiner Schrift:
* Bitte im Text Links setzen wo sinnvoll (Bold Monday, MetaDesign, ...)
* «... und könnte theoretisch sogar auch eines Tages eine Systemschriften bei Apple werden.» vielleicht besser «... und könnte in Kommenden Betriebssystemen mit ausgeliefert werden.» – möglich ja, aber wird wohl nicht geschehen.
* Ich würde entweder das IBM-Logo verwenden oder die Plex. Nicht aber das Logo «halb» nachbauen. 
* Die Fonts in der Detailansicht sind irgendwie verhackt. (siehe unten)
* Im Moment verschwindet das Hamburger-Menü in deinem Header-Bild. Gleiche Hintergrundfarbe und sogar noch die Streifen, die sich ähnlich sind. Hast du einen Vorschlag um dieses Problem zu minimieren?
* Quellen zum Text?

![screen shot 2018-07-05 at 18 31 25](https://user-images.githubusercontent.com/992878/42335749-a941e9da-8081-11e8-9498-835a66bea3ea.png)

**Comment by stfffchs** [comment]
@signalwerk bzgl. Quellen, wollen wir da nich einen Absatz mit Quellen machen? Bei allen gleich?

**Comment by signalwerk** [comment]
@stfffchs das ist bestimmt eine frage die @larsmaeder @marc-hatt @tioemayer @matthiasmeierkoch vom Team Detailseite beantworten kann 😉
