### ISSUE TITLE
Faustina – Review

### ISSUE THREAD

**Issue by signalwerk** [logrinto/IAD2017.schriftmuster#66]
@severinkilchhofer hier ein paar Inputs zu deiner Site:

- [x] Bitte im Text Links setzen wo sinnvoll (Omnibus-Type, Latinotype, ...)
- [x] Font ist in den SVG's nicht in Outlines umgewandelt (falsche Darstellung). Deshalb kann ich zum Muster im Moment auch nicht viel sagen.
- [x] gibt es einen Grund für die Dreiecke in den Darstellungen? Ist das ein Hausdach? 
- [x] «x-Höhe» statt «X Höhe»
- [x] «Beim Format handelt es sich um ein OpenType PostScript (.otf).» allenfalls raus? Wir verwenden ja meist Woff mit PS-Outlines.
- [x] «Die Schrift Faustina wird momentan auf 1600 Webseiten eingesetzt.» würde ich allenfalls auch weg lassen. Ist sehr ungewiss und die Zahl änder wohl ständig.
- [x] Quellen zum Text?

**Comment by severinkilchhofer** [comment]
Zu deiner Frage: gibt es einen Grund für die Dreiecke in den Darstellungen? Ist das ein Hausdach? 

Nein, es gibt keinen bestimmten Grund dafür. Diese Dreiecke hast du richtig interpretiert. Es ist ein Hausdach. Ich habe mich für dieses Entschieden, weil ich die Cover Texte mit «Architektur-Wörter» bestückt habe :)
