### ISSUE TITLE
Raleway – Review

### ISSUE THREAD

**Issue by signalwerk** [logrinto/IAD2017.schriftmuster#69]
@niciwatri hier ein paar Meinungen zur Schrift:
* Du hast deine Links nun mit einer `id` im Grundtext formatiert. Abgesehen von der Diskussion in #55 solltest du die selbe ID nie zweimal auf einer Seite verwenden. In so einem Fall kannst du mit Klassen arbeiten.
* Ich finde deine typografische Darstellung von einigen charakterstarken Zeichen gelungen!
* Das Headline-Bild vermittelt für mich weniger grafische Feinheit als das Folgebild. Allenfalls könnte der Hintergrund nicht nur das «W» zeigen? Und auch er Titel der Raleway könnte man allenfalls noch gekonnter mit dem Hintergrund verbinden, statt ihn mit einem Schatten möglichst ab zu grenzen. Was meinst du?
* Ich finde du hast den Text durchdacht aufgebaut!
* Quellen zum Text?

**Comment by niciwatri** [comment]
@signalwerk danke für deine Kommentare:

– Hatte vergessen dass man id nur einmal verwendet. Habe davor aber sowieso mit einer neuen Klasse probiert und dies hat nicht funktioniert. Auch mit dem a tag und dann die Klasse hat es nicht geklappt. Ich denke, dass eine andere Klasse die einem übergeordneten Container zugeteilt ist, meine überschreibt. Was gibt es denn noch für eine Lösung? und wie bringe ich diese Pfeile bei meinen Links im Lauftext raus?
– Beim Headline-Bild habe ich bewusst nur das "W" in den Hintergrund gestellt. Da ich finde es ist das Zeichen, welches sich von anderen Schriften am stärksten abhebt. Und die anderen wichtigen Zeichen zeige ich ja dann im nächsten Bild. --> Werde aber trotzdem nochmals das Headline-Bild überarbeiten, um eine bessere Einheit zu schaffen. 
– Quellen habe ich noch eingefügt, merci für den Hinweis!

**Comment by signalwerk** [comment]
@niciwatri 
* Ja die Links sind nun [hier](https://github.com/logrinto/IAD2017.schriftmuster/blob/master/docs/assets/styles/main.css#L91-L97) global definiert. Das war am Anfang nicht so, da ich diese nicht formatiert hate. Ich habe den Pfeil eingefügt. Aber natürlich kann der auch raus. @larsmaeder @marc-hatt @tioemayer @matthiasmeierkoch haben das Sagen, wie Links nun global aussehen.
* Wenn du dich auf das W konzentrieren möchtest, kann ich das auch verstehen. Allenfalls kannst du dann aber mit der «Textur» mehr machen. Kennst du die Arbeiten von [Ruder](https://www.google.ch/search?biw=1592&bih=935&tbm=isch&sa=1&ei=ohpFW46-Eo3ygQai5obgDg&q=emil+ruder+typographie&oq=emil+ruder+typog&gs_l=img.3.0.0l2j0i24k1l2.22836.23763.0.25043.5.2.0.3.3.0.188.363.0j2.2.0....0...1c.1.64.img..0.5.371....0.woSc1YgnRHc)?

**Comment by signalwerk** [comment]
@niciwatri ja lass uns am Samstag noch kurz über dieses Thema sprechen.
